create table if not exists public.proposal_committee_decisions(
 id uuid primary key default gen_random_uuid(), submission_id uuid not null references public.citizen_submissions(id) on delete cascade, committee_member_id uuid not null references public.profiles(id), version integer not null, decision text not null check(decision in ('draft','accepted','returned','rejected','held')), rationale text not null default '', conditions text not null default '', committee_note text not null default '', decided_at timestamptz, created_at timestamptz not null default now(), unique(submission_id,version));
alter table public.proposal_committee_decisions enable row level security;
revoke all on public.proposal_committee_decisions from anon; grant select,insert on public.proposal_committee_decisions to authenticated;
drop policy if exists committee_decisions_select on public.proposal_committee_decisions;
create policy committee_decisions_select on public.proposal_committee_decisions for select to authenticated using(committee_member_id=(select auth.uid()) or exists(select 1 from public.workflow_role_assignments a join public.workflow_roles r on r.id=a.workflow_role_id where a.user_id=(select auth.uid()) and a.is_active and r.is_active and r.code='committee') or exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='admin'));
drop policy if exists committee_decisions_insert on public.proposal_committee_decisions;
create policy committee_decisions_insert on public.proposal_committee_decisions for insert to authenticated with check(committee_member_id=(select auth.uid()) and exists(select 1 from public.workflow_role_assignments a join public.workflow_roles r on r.id=a.workflow_role_id where a.user_id=(select auth.uid()) and a.is_active and r.is_active and r.code='committee'));
create or replace function public.workflow_latest_committee_decision(p_submission_id uuid) returns jsonb language sql security invoker set search_path='' as $$ select to_jsonb(x) from (select d.*,p.display_name committee_member_name from public.proposal_committee_decisions d left join public.profiles p on p.id=d.committee_member_id where d.submission_id=p_submission_id order by d.version desc limit 1) x $$;
revoke all on function public.workflow_latest_committee_decision(uuid) from public,anon; grant execute on function public.workflow_latest_committee_decision(uuid) to authenticated;
create or replace function public.workflow_save_committee_decision(p_submission_id uuid,p_decision text,p_rationale text,p_conditions text default '',p_committee_note text default '') returns integer language plpgsql security invoker set search_path='' as $$
declare v_version int; begin
 if p_decision not in ('draft','accepted','returned','rejected','held') then raise exception 'Invalid committee decision'; end if;
 if not exists(select 1 from public.workflow_role_assignments a join public.workflow_roles r on r.id=a.workflow_role_id where a.user_id=auth.uid() and a.is_active and r.is_active and r.code='committee' and r.step_order=7) then raise exception 'Committee role access required'; end if;
 if not exists(select 1 from public.citizen_submissions s where s.id=p_submission_id and s.workflow_step=7) then raise exception 'Application is not at Committee stage'; end if;
 if not exists(select 1 from public.proposal_legal_reviews l where l.submission_id=p_submission_id and l.review_status='completed') then raise exception 'Completed legal review is required before committee decision'; end if;
 if p_decision<>'draft' and nullif(trim(coalesce(p_rationale,'')),'') is null then raise exception 'Committee rationale is required'; end if;
 select coalesce(max(version),0)+1 into v_version from public.proposal_committee_decisions where submission_id=p_submission_id;
 insert into public.proposal_committee_decisions(submission_id,committee_member_id,version,decision,rationale,conditions,committee_note,decided_at) values(p_submission_id,auth.uid(),v_version,p_decision,coalesce(p_rationale,''),coalesce(p_conditions,''),coalesce(p_committee_note,''),case when p_decision='draft' then null else now() end);
 return v_version; end $$;
revoke all on function public.workflow_save_committee_decision(uuid,text,text,text,text) from public,anon; grant execute on function public.workflow_save_committee_decision(uuid,text,text,text,text) to authenticated;